/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/digitalocean_icon.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.095, 0, 0.412]} scale={[0.48, 0.957, 0.484]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano_1.geometry}
          material={materials.Materiai_do_dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano_2.geometry}
          material={materials.Material_do}
        />
      </group>
      <group position={[-0.946, 0, 1.271]} scale={[0.375, 0.747, 0.378]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano001_1.geometry}
          material={materials.Materiai_do_dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano001_2.geometry}
          material={materials.Material_do}
        />
      </group>
      <group position={[-1.636, 0, 0.588]} scale={[0.32, 0.638, 0.323]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano002_1.geometry}
          material={materials.Material_do}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano002_2.geometry}
          material={materials.Materiai_do_dark}
        />
      </group>
      <group position={[0.388, 0, -0.644]} scale={2.517}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro002.geometry}
          material={materials.Material_do}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro002_1.geometry}
          material={materials.Materiai_do_dark}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/digitalocean_icon.glb')

