/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alex human (https://sketchfab.com/alex-human)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/docker-logo-606f87d0394248b1bf488dcba121ffa7
Title: Docker Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/docker_icon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.blue} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.white}
      />
    </group>
  )
}

useGLTF.preload('/models/docker_icon.glb')

