/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/fastapi_icon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Círculo.geometry}
        material={materials['Material.001']}
        position={[0.113, 0, 0]}
        scale={1.603}
      />
    </group>
  )
}

useGLTF.preload('/models/fastapi_icon.glb')

