/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DemiGod1410 (https://sketchfab.com/DemiGod1410)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/figma-5a66a770e9864e50870e5d5f17c4b211
Title: Figma
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/figma_icon.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.figma_Texture_0.geometry}
          material={materials.Texture}
          position={[-1.049, 0, 1.824]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/figma_icon.glb')

