/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mastergames2435 (https://sketchfab.com/mastergames243534)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/git-logo-01e9bc6656f0423bb4c68bff7aae4b99
Title: Git logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/git_icon.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['SVGMat.006']}
          rotation={[Math.PI / 2, 0, 0]}
          scale={16.686}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/git_icon.glb')

