/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/illustrator_icon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066.geometry}
        material={materials['base_0.001']}
        scale={[0.666, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve021.geometry}
        material={materials['SVGMat.003']}
        position={[0.196, -0.843, 0.843]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={24.823}
      />
    </group>
  )
}

useGLTF.preload('/models/illustrator_icon.glb')

