/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/java_icon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve010.geometry}
        material={materials['SVGMat.008']}
        position={[0.194, -1.433, 1.189]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={3.265}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve013.geometry}
        material={materials['SVGMat.011']}
        position={[0.194, -0.318, -0.001]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={3.265}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials.white}
        scale={[0.666, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/models/java_icon.glb')

