/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/mysql_icon.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={1.615}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials['Material.001']}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve010.geometry}
          material={materials['Material.048']}
          position={[0, 0, 0.095]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[18.689, 13.456, 18.689]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mysql_icon.glb')

